/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import org.bson.types.ObjectId;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class FrmCambiarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form FrmCambiarContraseña
     */
    private ObjectId objectId;
    public FrmCambiarContraseña(ObjectId objectID) {
        initComponents();
        this.objectId = objectID;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public JLabel getLblContrseñaActual() {
        return lblContrseñaActual;
    }

    public JLabel getLblContrseñaAnterior() {
        return lblContrseñaAnterior;
    }

    public JLabel getLblNombreApellido() {
        return lblNombreApellido;
    }

    public JPasswordField getPswContraseniaActual() {
        return pswContraseniaActual;
    }

    public JPasswordField getPswContraseniaAnterior() {
        return pswContraseniaAnterior;
    }

    public ObjectId getObjectId() {
        return objectId;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreApellido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblContrseñaAnterior = new javax.swing.JLabel();
        lblContrseñaActual = new javax.swing.JLabel();
        pswContraseniaActual = new javax.swing.JPasswordField();
        pswContraseniaAnterior = new javax.swing.JPasswordField();
        lblCargo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario_gerente.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 60));

        lblNombreApellido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreApellido.setText("jLabel3");
        jPanel1.add(lblNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setText("CONTRASEÑA ANTERIOR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel1.setText("CONTRASEÑA ACTUAL:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 240, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 240, 20));

        lblContrseñaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblContrseñaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 30, -1));

        lblContrseñaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblContrseñaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 30, -1));

        pswContraseniaActual.setText("********************");
        pswContraseniaActual.setToolTipText("");
        pswContraseniaActual.setBorder(null);
        jPanel1.add(pswContraseniaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, 20));

        pswContraseniaAnterior.setText("********************");
        pswContraseniaAnterior.setBorder(null);
        jPanel1.add(pswContraseniaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, 20));

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(204, 0, 0));
        lblCargo.setText("jLabel4");
        jPanel1.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 380, 30));

        btnGuardar.setBackground(new java.awt.Color(21, 101, 192));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblContrseñaActual;
    private javax.swing.JLabel lblContrseñaAnterior;
    private javax.swing.JLabel lblNombreApellido;
    private javax.swing.JPasswordField pswContraseniaActual;
    private javax.swing.JPasswordField pswContraseniaAnterior;
    // End of variables declaration//GEN-END:variables
}
