/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlActualizarAdministradores extends javax.swing.JPanel {

    /**
     * Creates new form PnlActualizarAdministradores
     */
    public PnlActualizarAdministradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloTelefono = new javax.swing.JLabel();
        lblTituloAdministrador = new javax.swing.JLabel();
        lblTituloApellido = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloCargo = new javax.swing.JLabel();
        lblTituloSueldo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblAlertaTelefono = new javax.swing.JLabel();
        lblAlertaAdministrador = new javax.swing.JLabel();
        lblAlertaApellido = new javax.swing.JLabel();
        lblAlertaNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblAlertaSueldo = new javax.swing.JLabel();
        lblAlertaCargo = new javax.swing.JLabel();
        lblTituloSueldo1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblAlertaSueldo1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        btnIntroduccion = new javax.swing.JButton();
        btnIntroduccion1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTelefono.setText("TELEFONO");
        jPanel1.add(lblTituloTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblTituloAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloAdministrador.setText("USUARIO ADMINISTRADOR");
        jPanel1.add(lblTituloAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lblTituloApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloApellido.setText("APELLIDO");
        jPanel1.add(lblTituloApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNombre.setText("NOMBRE");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblTituloCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloCargo.setText("CARGO");
        jPanel1.add(lblTituloCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        lblTituloSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSueldo.setText("SUELDO");
        jPanel1.add(lblTituloSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 20));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 300, 20));

        lblAlertaTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 20, 20));

        lblAlertaAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 20, 20));

        lblAlertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 20, 20));

        lblAlertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("ACTUALIZAR DATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 290, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 290, 20));

        lblAlertaSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 20, 20));

        lblAlertaCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 20, 20));

        lblTituloSueldo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSueldo1.setText("CÉDULA");
        jPanel1.add(lblTituloSueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 290, 20));

        lblAlertaSueldo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaSueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 20, 20));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Ingrese su cédula");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 300, 20));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Ingrese su nombre");
        jTextField3.setBorder(null);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 20));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Ingrese su apellido");
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 20));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("Ingrese su usuario");
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 20));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("Ingrese su número de teléfono");
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 20));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("Ingrese su cargo en la empresa");
        jTextField7.setBorder(null);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 300, 20));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText("Sueldo del Administrador");
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 300, 20));

        btnIntroduccion.setBackground(new java.awt.Color(21, 101, 192));
        btnIntroduccion.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnIntroduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnIntroduccion.setText("CAMBIAR CONTRASEÑA");
        btnIntroduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnIntroduccion.setBorderPainted(false);
        btnIntroduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntroduccion.setIconTextGap(15);
        jPanel1.add(btnIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 320, 60));

        btnIntroduccion1.setBackground(new java.awt.Color(21, 101, 192));
        btnIntroduccion1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnIntroduccion1.setForeground(new java.awt.Color(255, 255, 255));
        btnIntroduccion1.setText("GUARDAR");
        btnIntroduccion1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnIntroduccion1.setBorderPainted(false);
        btnIntroduccion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntroduccion1.setIconTextGap(15);
        jPanel1.add(btnIntroduccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 320, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntroduccion;
    private javax.swing.JButton btnIntroduccion1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblAlertaAdministrador;
    private javax.swing.JLabel lblAlertaApellido;
    private javax.swing.JLabel lblAlertaCargo;
    private javax.swing.JLabel lblAlertaNombre;
    private javax.swing.JLabel lblAlertaSueldo;
    private javax.swing.JLabel lblAlertaSueldo1;
    private javax.swing.JLabel lblAlertaTelefono;
    private javax.swing.JLabel lblTituloAdministrador;
    private javax.swing.JLabel lblTituloApellido;
    private javax.swing.JLabel lblTituloCargo;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloSueldo;
    private javax.swing.JLabel lblTituloSueldo1;
    private javax.swing.JLabel lblTituloTelefono;
    // End of variables declaration//GEN-END:variables
}
