/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlActualizarAdministradores extends javax.swing.JPanel {

    /**
     * Creates new form PnlActualizarAdministradores
     */
    public PnlActualizarAdministradores() {
        initComponents();
    }

    public JButton getBtnCambiarContrasenia() {
        return btnCambiarContrasenia;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JSeparator getjSeparator9() {
        return jSeparator9;
    }

    public JLabel getLblAlertaAdministrador() {
        return lblAlertaAdministrador;
    }

    public JLabel getLblAlertaApellido() {
        return lblAlertaApellido;
    }

    public JLabel getLblAlertaCargo() {
        return lblAlertaCargo;
    }

    public JLabel getLblAlertaCedula() {
        return lblAlertaCedula;
    }

    public JLabel getLblAlertaNombre() {
        return lblAlertaNombre;
    }

    public JLabel getLblAlertaSueldo() {
        return lblAlertaSueldo;
    }

    public JLabel getLblAlertaTelefono() {
        return lblAlertaTelefono;
    }

    public JLabel getLblTituloAdministrador() {
        return lblTituloAdministrador;
    }

    public JLabel getLblTituloApellido() {
        return lblTituloApellido;
    }

    public JLabel getLblTituloCargo() {
        return lblTituloCargo;
    }

    public JLabel getLblTituloCedula() {
        return lblTituloCedula;
    }

    public JLabel getLblTituloNombre() {
        return lblTituloNombre;
    }

    public JLabel getLblTituloSueldo() {
        return lblTituloSueldo;
    }

    public JLabel getLblTituloTelefono() {
        return lblTituloTelefono;
    }

    public JTextField getTxtAdministrador() {
        return txtAdministrador;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextField getTxtCargo() {
        return txtCargo;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JPanel getPnlContenido() {
        return pnlContenido;
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        lblTituloTelefono = new javax.swing.JLabel();
        lblTituloAdministrador = new javax.swing.JLabel();
        lblTituloApellido = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloCargo = new javax.swing.JLabel();
        lblTituloSueldo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblAlertaTelefono = new javax.swing.JLabel();
        lblAlertaAdministrador = new javax.swing.JLabel();
        lblAlertaApellido = new javax.swing.JLabel();
        lblAlertaNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblAlertaSueldo = new javax.swing.JLabel();
        lblAlertaCargo = new javax.swing.JLabel();
        lblTituloCedula = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblAlertaCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtAdministrador = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        btnCambiarContrasenia = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTelefono.setText("TELEFONO");
        pnlContenido.add(lblTituloTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblTituloAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloAdministrador.setText("USUARIO ADMINISTRADOR");
        pnlContenido.add(lblTituloAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lblTituloApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloApellido.setText("APELLIDO");
        pnlContenido.add(lblTituloApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNombre.setText("NOMBRE");
        pnlContenido.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblTituloCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloCargo.setText("CARGO");
        pnlContenido.add(lblTituloCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        lblTituloSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSueldo.setText("SUELDO");
        pnlContenido.add(lblTituloSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 20));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 300, 20));

        lblAlertaTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 20, 20));

        lblAlertaAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 20, 20));

        lblAlertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 20, 20));

        lblAlertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("ACTUALIZAR DATOS");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 290, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 290, 20));

        lblAlertaSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 20, 20));

        lblAlertaCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 20, 20));

        lblTituloCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloCedula.setText("CÉDULA");
        pnlContenido.add(lblTituloCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        pnlContenido.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 290, 20));

        lblAlertaCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 20, 20));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese su cédula");
        txtCedula.setBorder(null);
        pnlContenido.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 300, 20));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        pnlContenido.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 20));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("Ingrese su apellido");
        txtApellido.setBorder(null);
        pnlContenido.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 20));

        txtAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAdministrador.setForeground(new java.awt.Color(153, 153, 153));
        txtAdministrador.setText("Ingrese su usuario");
        txtAdministrador.setBorder(null);
        pnlContenido.add(txtAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 20));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingrese su número de teléfono");
        txtTelefono.setBorder(null);
        pnlContenido.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 20));

        txtCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(153, 153, 153));
        txtCargo.setText("Ingrese su cargo en la empresa");
        txtCargo.setBorder(null);
        pnlContenido.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 300, 20));

        txtSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(153, 153, 153));
        txtSueldo.setText("Sueldo del Administrador");
        txtSueldo.setBorder(null);
        pnlContenido.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 300, 20));

        btnCambiarContrasenia.setBackground(new java.awt.Color(21, 101, 192));
        btnCambiarContrasenia.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnCambiarContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarContrasenia.setText("CAMBIAR CONTRASEÑA");
        btnCambiarContrasenia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCambiarContrasenia.setBorderPainted(false);
        btnCambiarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarContrasenia.setIconTextGap(15);
        pnlContenido.add(btnCambiarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 320, 60));

        btnGuardar.setBackground(new java.awt.Color(21, 101, 192));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setIconTextGap(15);
        pnlContenido.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 320, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarContrasenia;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAlertaAdministrador;
    private javax.swing.JLabel lblAlertaApellido;
    private javax.swing.JLabel lblAlertaCargo;
    private javax.swing.JLabel lblAlertaCedula;
    private javax.swing.JLabel lblAlertaNombre;
    private javax.swing.JLabel lblAlertaSueldo;
    private javax.swing.JLabel lblAlertaTelefono;
    private javax.swing.JLabel lblTituloAdministrador;
    private javax.swing.JLabel lblTituloApellido;
    private javax.swing.JLabel lblTituloCargo;
    private javax.swing.JLabel lblTituloCedula;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloSueldo;
    private javax.swing.JLabel lblTituloTelefono;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JTextField txtAdministrador;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
