/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlNuevoAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form PnlNuevoAdministrador
     */
    public PnlNuevoAdministrador() {
        initComponents();
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public JTextField getTxtCargo() {
        return txtCargo;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JPasswordField getPswContrasenia() {
        return pswContrasenia;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtSueldo() {
        return txtSueldo;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JTextField getTxtNombreUsuario() {
        return txtNombreUsuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloApellido = new javax.swing.JLabel();
        lblTituloAdministrador = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblAlertaCedula = new javax.swing.JLabel();
        lblAlertaUsuario = new javax.swing.JLabel();
        lblAlertaApellido = new javax.swing.JLabel();
        lblAlertaNombre = new javax.swing.JLabel();
        lblTituloTelefono = new javax.swing.JLabel();
        lblTituloCargo = new javax.swing.JLabel();
        lblTituloSueldo = new javax.swing.JLabel();
        lblTituloContraseña = new javax.swing.JLabel();
        lblAlertaContraseña = new javax.swing.JLabel();
        lblAlertaSueldo = new javax.swing.JLabel();
        lblAlertaCargo = new javax.swing.JLabel();
        lblAlertaTelefono = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        pswContrasenia = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("NUEVO ADMINISTRADOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloNombre.setText("NOMBRE");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblTituloApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloApellido.setText("APELLIDO");
        jPanel1.add(lblTituloApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTituloAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloAdministrador.setText("USUARIO ADMINISTRADOR");
        jPanel1.add(lblTituloAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lblCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCedula.setText("CÉDULA");
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblAlertaCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 20, 20));

        lblAlertaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 20, 20));

        lblAlertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 20, 20));

        lblAlertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 20, 20));

        lblTituloTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloTelefono.setText("TELEFONO");
        jPanel1.add(lblTituloTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        lblTituloCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloCargo.setText("CARGO");
        jPanel1.add(lblTituloCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        lblTituloSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloSueldo.setText("SUELDO");
        jPanel1.add(lblTituloSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        lblTituloContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloContraseña.setText("CONTRASEÑA");
        jPanel1.add(lblTituloContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        lblAlertaContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 20, 20));

        lblAlertaSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 20, 20));

        lblAlertaCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 20, 20));

        lblAlertaTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 20, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 20));

        jSeparator10.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 300, 20));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 290, 20));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 290, 20));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 290, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 290, 20));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese la cédula del Administrador");
        txtCedula.setBorder(null);
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 455, 300, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 135, 300, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreUsuario.setText("Ingrese el nombre del administrador");
        txtNombreUsuario.setBorder(null);
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 355, 300, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("Ingrese el apellido del usuario");
        txtApellido.setBorder(null);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 245, 300, -1));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefono.setText("Ingrese su número de telefono");
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 290, 20));

        txtCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(153, 153, 153));
        txtCargo.setText("Ingrese su cargo en la empresa");
        txtCargo.setBorder(null);
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 290, 20));

        txtSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(153, 153, 153));
        txtSueldo.setText("Sueldo del Administrador");
        txtSueldo.setBorder(null);
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 290, 20));

        pswContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        pswContrasenia.setText("*******************************");
        pswContrasenia.setBorder(null);
        jPanel1.add(pswContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 290, 20));

        btnGuardar.setBackground(new java.awt.Color(21, 101, 192));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-25.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuardar.setIconTextGap(15);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAlertaApellido;
    private javax.swing.JLabel lblAlertaCargo;
    private javax.swing.JLabel lblAlertaCedula;
    private javax.swing.JLabel lblAlertaContraseña;
    private javax.swing.JLabel lblAlertaNombre;
    private javax.swing.JLabel lblAlertaSueldo;
    private javax.swing.JLabel lblAlertaTelefono;
    private javax.swing.JLabel lblAlertaUsuario;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblTituloAdministrador;
    private javax.swing.JLabel lblTituloApellido;
    private javax.swing.JLabel lblTituloCargo;
    private javax.swing.JLabel lblTituloContraseña;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloSueldo;
    private javax.swing.JLabel lblTituloTelefono;
    private javax.swing.JPasswordField pswContrasenia;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
