/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlNuevoEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PnlNuevoEmpleado
     */
    public PnlNuevoEmpleado() {
        initComponents();
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JLabel getLblAlertaApellido() {
        return lblAlertaApellido;
    }

    public JLabel getLblAlertaContraseña() {
        return lblAlertaContraseña;
    }

    public JLabel getLblAlertaNombre() {
        return lblAlertaNombre;
    }

    public JLabel getLblAlertaSueldo() {
        return lblAlertaSueldo;
    }

    public JLabel getLblAlertaTelefono() {
        return lblAlertaTelefono;
    }

    public JLabel getLblAlertaUsuario() {
        return lblAlertaUsuario;
    }

    public JLabel getLblCedulaEmpleado() {
        return lblCedulaEmpleado;
    }

    public JPasswordField getPswContraseniaEmpleado() {
        return pswContraseniaEmpleado;
    }

    public JTextField getTxtApellidoEmpleado() {
        return txtApellidoEmpleado;
    }

    public JTextField getTxtCedulaEmpleado() {
        return txtCedulaEmpleado;
    }

    public JTextField getTxtNombreEmpleado() {
        return txtNombreEmpleado;
    }

    public JTextField getTxtSueldoEmpleado() {
        return txtSueldoEmpleado;
    }

    public JTextField getTxtTelefonoEmpleado() {
        return txtTelefonoEmpleado;
    }

    public JTextField getTxtUsuarioEmpleado() {
        return txtUsuarioEmpleado;
    }

    public JLabel getLblAlertaTextoSueldo() {
        return lblAlertaTextoSueldo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lblAlertaNombre = new javax.swing.JLabel();
        lblAlertaApellido = new javax.swing.JLabel();
        lblAlertaUsuario = new javax.swing.JLabel();
        lblAlertaTelefono = new javax.swing.JLabel();
        lblAlertaContraseña = new javax.swing.JLabel();
        lblCedulaEmpleado = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lblAlertaSueldo = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        txtCedulaEmpleado = new javax.swing.JTextField();
        txtSueldoEmpleado = new javax.swing.JTextField();
        pswContraseniaEmpleado = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        lblAlertaTextoSueldo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setText("NUEVO EMPLEADO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("NOMBRE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("APELLIDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, 20));

        jSeparator3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 290, 20));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 290, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        lblAlertaNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 20, 20));

        lblAlertaApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 20, 20));

        lblAlertaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 20, 20));

        lblAlertaTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 20, 20));

        lblAlertaContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 20, 20));

        lblCedulaEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblCedulaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 20, 20));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 290, 20));

        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 290, 20));

        jSeparator6.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 290, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("TELEFONO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("CÉDULA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("SUELDO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 290, 20));

        lblAlertaSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jPanel1.add(lblAlertaSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 20, 20));

        txtNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreEmpleado.setText("Ingrese el nombre del empleado");
        txtNombreEmpleado.setBorder(null);
        jPanel1.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 20));

        txtApellidoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoEmpleado.setText("Ingrese el apellido del empleado");
        txtApellidoEmpleado.setBorder(null);
        jPanel1.add(txtApellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 20));

        txtUsuarioEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuarioEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuarioEmpleado.setText("Ingrese el nombre de usuario");
        txtUsuarioEmpleado.setBorder(null);
        jPanel1.add(txtUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, 20));

        txtTelefonoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefonoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoEmpleado.setText("Ingrese el número de teléfono");
        txtTelefonoEmpleado.setBorder(null);
        jPanel1.add(txtTelefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 290, 20));

        txtCedulaEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedulaEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaEmpleado.setText("Ingrese la cédula del empleado");
        txtCedulaEmpleado.setBorder(null);
        jPanel1.add(txtCedulaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 290, 20));

        txtSueldoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSueldoEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        txtSueldoEmpleado.setText("Ingrese el sueldo del empleado");
        txtSueldoEmpleado.setBorder(null);
        jPanel1.add(txtSueldoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 290, 20));

        pswContraseniaEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        pswContraseniaEmpleado.setText("****************************");
        pswContraseniaEmpleado.setBorder(null);
        jPanel1.add(pswContraseniaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 290, 20));

        btnGuardar.setBackground(new java.awt.Color(21, 101, 192));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-25.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setIconTextGap(15);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 300, 60));

        lblAlertaTextoSueldo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblAlertaTextoSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAlertaApellido;
    private javax.swing.JLabel lblAlertaContraseña;
    private javax.swing.JLabel lblAlertaNombre;
    private javax.swing.JLabel lblAlertaSueldo;
    private javax.swing.JLabel lblAlertaTelefono;
    private javax.swing.JLabel lblAlertaTextoSueldo;
    private javax.swing.JLabel lblAlertaUsuario;
    private javax.swing.JLabel lblCedulaEmpleado;
    private javax.swing.JPasswordField pswContraseniaEmpleado;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtCedulaEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSueldoEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
