package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.bson.types.ObjectId;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class FrmMenu extends javax.swing.JFrame {

    private String nombreDeUsuario;
    private ObjectId objectID;
    private static FrmMenu frmMenu= null;
    private FrmMenu(String nombreDeUsuario) {
        initComponents();
        this.nombreDeUsuario = nombreDeUsuario;
       
    }
    
    public static FrmMenu getInstance(String nombreUsuario){
        if(frmMenu == null){
           frmMenu = new FrmMenu(nombreUsuario);
        }
        return frmMenu;
    }
    
    public static  void reiniciarInstancia(){
        frmMenu = null;
    }
    
    public void setObjectID(ObjectId objectID){
        this.objectID = objectID;
    }
    
    public ObjectId getObjectId(){
        return  objectID;
    }

    public String getNombreDeUsuario() {
        return nombreDeUsuario;
    }

    public void setNombreDeUsuario(String nombreDeUsuario) {
        this.nombreDeUsuario = nombreDeUsuario;
    }

    public JButton getBtnAdministrador() {
        return btnAdministrador;
    }

    public void setBtnAdministrador(JButton btnAdministrador) {
        this.btnAdministrador = btnAdministrador;
    }

    public JButton getBtnIntroduccion() {
        return btnIntroduccion;
    }

    public void setBtnIntroduccion(JButton btnIntroduccion) {
        this.btnIntroduccion = btnIntroduccion;
    }

    public JLabel getLblNombreUsuarioLoing() {
        return lblNombreUsuarioLoing;
    }

    public void setLblNombreUsuarioLoing(JLabel lblNombreUsuarioLoing) {
        this.lblNombreUsuarioLoing = lblNombreUsuarioLoing;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public void setLblCargo(JLabel lblCargo) {
        this.lblCargo = lblCargo;
    }
    
    public JPanel getPnlContenido() {
        return pnlContenido;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnEmpleado() {
        return btnEmpleado;
    }

    public JButton getBtnProducto() {
        return btnProducto;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnIntroduccion = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreUsuarioLoing = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngwing.com (6).png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(21, 101, 192));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cerrar-sesión-35.png"))); // NOI18N
        btnCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.setIconTextGap(15);
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 280, 60));

        btnIntroduccion.setBackground(new java.awt.Color(21, 101, 192));
        btnIntroduccion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnIntroduccion.setForeground(new java.awt.Color(255, 255, 255));
        btnIntroduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-25.png"))); // NOI18N
        btnIntroduccion.setText("INTRODUCCIÓN");
        btnIntroduccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnIntroduccion.setBorderPainted(false);
        btnIntroduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntroduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIntroduccion.setIconTextGap(15);
        jPanel2.add(btnIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 60));

        btnAdministrador.setBackground(new java.awt.Color(21, 101, 192));
        btnAdministrador.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-gerente-35.png"))); // NOI18N
        btnAdministrador.setText("ADMINISTRADORES");
        btnAdministrador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnAdministrador.setBorderPainted(false);
        btnAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministrador.setIconTextGap(15);
        jPanel2.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 60));

        btnEmpleado.setBackground(new java.awt.Color(21, 101, 192));
        btnEmpleado.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuarios-35 (1).png"))); // NOI18N
        btnEmpleado.setText("EMPLEADOS");
        btnEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleado.setIconTextGap(15);
        jPanel2.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 60));

        btnProducto.setBackground(new java.awt.Color(21, 101, 192));
        btnProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-productos-35.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProducto.setBorderPainted(false);
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducto.setIconTextGap(15);
        jPanel2.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        jButton15.setBackground(new java.awt.Color(21, 101, 192));
        jButton15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuarios-35.png"))); // NOI18N
        jButton15.setText("CLIENTES");
        jButton15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton15.setBorderPainted(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.setIconTextGap(15);
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, 60));

        jButton16.setBackground(new java.awt.Color(21, 101, 192));
        jButton16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-categorizar-35.png"))); // NOI18N
        jButton16.setText("CATEGORIA");
        jButton16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton16.setIconTextGap(15);
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 280, 60));

        jButton17.setBackground(new java.awt.Color(21, 101, 192));
        jButton17.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-calculadora-35.png"))); // NOI18N
        jButton17.setText("FACTURAR");
        jButton17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton17.setBorderPainted(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton17.setIconTextGap(15);
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 280, 60));

        jButton18.setBackground(new java.awt.Color(21, 101, 192));
        jButton18.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-postal-35.png"))); // NOI18N
        jButton18.setText("REPORTES");
        jButton18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton18.setBorderPainted(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton18.setIconTextGap(15);
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 280, 60));

        jButton19.setBackground(new java.awt.Color(21, 101, 192));
        jButton19.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ventas-totales-35.png"))); // NOI18N
        jButton19.setText("REPORTES");
        jButton19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton19.setBorderPainted(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton19.setIconTextGap(15);
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 280, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 750));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encabezado.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1000, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-refrescar-25.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        lblNombreUsuarioLoing.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreUsuarioLoing.setText("jLabel5");
        jPanel1.add(lblNombreUsuarioLoing, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuario-30.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 30));

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(204, 0, 51));
        lblCargo.setText("jLabel6");
        jPanel1.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 180, -1));

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    }//GEN-LAST:event_jLabel3MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnIntroduccion;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNombreUsuarioLoing;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
