/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlGestionarCategorias extends javax.swing.JPanel {

    /**
     * Creates new form PnlGestionarAdministradores
     */
    public PnlGestionarCategorias() {
        initComponents();
    }


    public JButton getBtnEliminar() {
        return btnEliminar1;
    }


    public JButton getBtnNuevoProducto() {
        return btnNuevoProducto;
    }

    public JPanel getPnlContenido() {
        return pnlContenido;
    }

    public JTable getTblProducto() {
        return tblProductos;
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevoProducto1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblAlertaUsuario = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("CATEGORIAS");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnNuevoProducto.setBackground(new java.awt.Color(21, 101, 192));
        btnNuevoProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lupa-25.png"))); // NOI18N
        btnNuevoProducto.setText("Buscar");
        btnNuevoProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnNuevoProducto.setBorderPainted(false);
        btnNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevoProducto.setIconTextGap(15);
        pnlContenido.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 130, 30));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        pnlContenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1000, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-35.png"))); // NOI18N
        pnlContenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Categoria:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnNuevoProducto1.setBackground(new java.awt.Color(21, 101, 192));
        btnNuevoProducto1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNuevoProducto1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-25.png"))); // NOI18N
        btnNuevoProducto1.setText("Actualizar");
        btnNuevoProducto1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnNuevoProducto1.setBorderPainted(false);
        btnNuevoProducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProducto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNuevoProducto1.setIconTextGap(15);
        jPanel2.add(btnNuevoProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        btnEliminar1.setBackground(new java.awt.Color(21, 101, 192));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-25.png"))); // NOI18N
        btnEliminar1.setText("Borrar");
        btnEliminar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnEliminar1.setBorderPainted(false);
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar1.setIconTextGap(15);
        jPanel2.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jTextField2.setText("Seleccione");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jTextField3.setText("Seleccione");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 30));

        pnlContenido.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 390, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setText("BUSCAR");
        pnlContenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jRadioButton1.setText("Categoria");
        pnlContenido.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jRadioButton2.setText("ID");
        pnlContenido.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlContenido.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 180, 20));

        lblAlertaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 20, 20));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Campo requerido");
        pnlContenido.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setText("Nombre de la categoría");
        jTextField1.setBorder(null);
        pnlContenido.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 160, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setText("GESTIONAR");
        pnlContenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoProducto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAlertaUsuario;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
