/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jairo Smith Bonilla Hidalgo
 */
public class PnlGestionarCategorias extends javax.swing.JPanel {

    /**
     * Creates new form PnlGestionarAdministradores
     */
    public PnlGestionarCategorias() {
        initComponents();
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnBauscar() {
        return btnBauscar;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JLabel getLblAlertaUsuario() {
        return lblAlertaUsuario;
    }

    public JLabel getLblBuscar() {
        return lblBuscar;
    }

    public JPanel getPnlContenido() {
        return pnlContenido;
    }

    public JRadioButton getRbtnCategoria() {
        return rbtnCategoria;
    }

    public JRadioButton getRbtnID() {
        return rbtnID;
    }

    public JTable getTblCategorias() {
        return tblCategorias;
    }

    public JTextField getTxtBuscarNombreCategoria() {
        return txtBuscarNombreCategoria;
    }

    public JTextField getTxtCategoria() {
        return txtCategoria;
    }

    public JTextField getTxtID1() {
        return txtID1;
    }




    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBauscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnCategoria = new javax.swing.JRadioButton();
        rbtnID = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblAlertaUsuario = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscarNombreCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("CATEGORIAS");
        pnlContenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnBauscar.setBackground(new java.awt.Color(21, 101, 192));
        btnBauscar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBauscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBauscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lupa-25.png"))); // NOI18N
        btnBauscar.setText("Buscar");
        btnBauscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnBauscar.setBorderPainted(false);
        btnBauscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBauscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBauscar.setIconTextGap(15);
        pnlContenido.add(btnBauscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 130, 30));

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        pnlContenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1000, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-35.png"))); // NOI18N
        pnlContenido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Categoria:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(21, 101, 192));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-25.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnActualizar.setBorderPainted(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnActualizar.setIconTextGap(15);
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        btnBorrar.setBackground(new java.awt.Color(21, 101, 192));
        btnBorrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-25.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnBorrar.setBorderPainted(false);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBorrar.setIconTextGap(15);
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, 30));

        txtCategoria.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCategoria.setText("Seleccione");
        jPanel2.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, 30));

        txtID1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtID1.setText("Seleccione");
        jPanel2.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 30));

        pnlContenido.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 390, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setText("BUSCAR");
        pnlContenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        buttonGroup1.add(rbtnCategoria);
        rbtnCategoria.setSelected(true);
        rbtnCategoria.setText("Categoria");
        pnlContenido.add(rbtnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        buttonGroup1.add(rbtnID);
        rbtnID.setText("ID");
        pnlContenido.add(rbtnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlContenido.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 180, 20));

        lblAlertaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        pnlContenido.add(lblAlertaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 20, 20));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Campo requerido");
        pnlContenido.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        txtBuscarNombreCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscarNombreCategoria.setText("Nombre de la categoría");
        txtBuscarNombreCategoria.setBorder(null);
        pnlContenido.add(txtBuscarNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 160, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setText("GESTIONAR");
        pnlContenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBauscar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlertaUsuario;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JRadioButton rbtnCategoria;
    private javax.swing.JRadioButton rbtnID;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtBuscarNombreCategoria;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtID1;
    // End of variables declaration//GEN-END:variables
}
